on:
  poll:
    url: ${{ secrets.API }}
    requestConfig:
      method: GET
      headers:
        Authorization: Bearer ${{ secrets.API_TOKEN }}
    itemsPath: items
    deduplicationKey: _id
jobs:
  request:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        run: echo "link:${{ on.poll.outputs.link }}"
      - name: Call API
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.URL }}
          headers: '{"Authorization":"Token ${{ secrets.TOKEN }}","Content-Type":"application/json"}'
          accept: 201
          timeout: 60000
          method: POST
          body: |
            {
              "url":"${{ on.poll.outputs.link }}", 
              "title": "<<<${{ on.poll.outputs.title }}>>>",
              "description":"<<<${{ on.poll.outputs.excerpt }}>>>"
            }
