on:
  rss:
    url: ${{ secrets.RSS_FEED }}
jobs:
  request:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - name: Character Escaping
        run: |
          echo 'INFO: { "url":"${{ on.rss.outputs.link }}","title":"${{ on.rss.outputs.title }}" }'
          echo "TITLE=$( echo "${{ on.rss.outputs.title }}" | sed 's/"/\"/g' )" >> $GITHUB_ENV
      - name: Call API
        uses: indiesdev/curl@v1.1
        id: api
        with:
          url: ${{ secrets.URL }}
          method: "POST"
          headers: '{"Authorization":"Token ${{ secrets.TOKEN }}","Content-Type":"application/json"}'
          accept: 201
          timeout: 60000
          body: '{ "url":"${{ on.rss.outputs.link }}","title":"${{ env.TITLE }}" }'
          log-response: false
